base_url = "https://wtzlas.github.io"

compile_sass = true

build_search_index = true

theme = "DeepThought"

taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", fees = true, paginate_by = 10 },
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"
render_emoji = true

[extra]
katex.enabled = true
katex.auto_render = true

chart.enabled = true
mermaid.enabled = true
galleria.enabled = true

navbar_items = [
    { code = "en", nav_items = [
        { url = "$BASE_URL/", name = "Home" },
        { url = "$BASE_URL/posts", name = "Posts" },
        { url = "$BASE_URL/tags", name = "Tags" },
        { url = "$BASE_URL/categories", name = "Categories" },
    ] },
]

[extra.favicon]
favicon_16x16 = "icons/favicon-16x16.png"
favicon_32x32 = "icons/favicon-32x32.png"
apple_touch_icon = "icons/apple-touch-icon.png"
safari_pinned_tab = "icons/safari-pinned-tab.svg"
webmanifest = "icons/site.webmanifest"

[extra.author]
name = "Wtz_LASR"
avatar = "images/avatar.png"

[extra.social]
email = "wtz_lasr#outlook.com"
github = "WtzLAS"
